(() => {
  'use strict';
  const CONFIG = window.MY_STUDY_PATH_CONFIG || {};
  const API_URL = String(CONFIG.API_URL || '').trim();
  const STEPS = [
    ['รู้จักตัวเอง','เลือกตามความรู้สึกจริงของเรา ไม่มีคำตอบถูกหรือผิด'],
    ['เส้นทางหลังจบ ม.3','เลือกเส้นทางที่กำลังสนใจในตอนนี้'],
    ['แผนการเรียน / สาขาที่สนใจ','จัดลำดับตัวเลือกที่อยากศึกษาต่อ'],
    ['สถาบันที่อยู่ในใจ','ระบุโรงเรียน วิทยาลัย หรือสถานศึกษาที่สนใจ'],
    ['อาชีพและการตัดสินใจ','มองไปข้างหน้าและสำรวจปัจจัยที่มีผลกับเรา'],
    ['สรุปเส้นทางของฉัน','ตรวจสอบข้อมูลก่อนยืนยัน']
  ];
  const LISTS = {
    subjects:['ภาษาไทย','คณิตศาสตร์','วิทยาศาสตร์','ภาษาอังกฤษ','สังคมศึกษา','คอมพิวเตอร์/เทคโนโลยี','ศิลปะ','ดนตรี','สุขศึกษาและพลศึกษา','ภาษาต่างประเทศเพิ่มเติม','การงานอาชีพ','อื่น ๆ'],
    interests:['การคำนวณ','การทดลอง','การแก้ปัญหา','คอมพิวเตอร์','เทคโนโลยี','การเขียนโปรแกรม','ภาษา','การอ่านและการเขียน','การพูดและนำเสนอ','การขาย','ธุรกิจ','การทำบัญชี','การออกแบบ','การวาดภาพ','การถ่ายภาพ','การทำวิดีโอ','ดนตรี','กีฬา','การดูแลผู้อื่น','การสอน','การทำอาหาร','งานช่าง','การสร้างสิ่งของ','สัตว์และธรรมชาติ','อื่น ๆ'],
    strengths:['คิดวิเคราะห์','คำนวณ','จดจำ','ใช้ภาษา','สื่อสาร','นำเสนอ','กล้าแสดงออก','ความคิดสร้างสรรค์','วางแผน','เป็นผู้นำ','ทำงานร่วมกับผู้อื่น','ช่วยเหลือผู้อื่น','ใช้เทคโนโลยี','ลงมือปฏิบัติ','มีความละเอียด','มีความรับผิดชอบ','อื่น ๆ'],
    pathways:[['ม.4 สายสามัญ','เรียนต่อระดับมัธยมศึกษาตอนปลาย'],['สายอาชีพ ปวช.','เรียนแบบเน้นทักษะวิชาชีพ'],['หลักสูตรเฉพาะทาง','เช่น กีฬา ดนตรี ศิลปะ หรือหลักสูตรเฉพาะด้าน'],['อื่น ๆ','เส้นทางอื่นที่สนใจ'],['ยังไม่แน่ใจ','สามารถสำรวจต่อและขอคำแนะนำได้']],
    m4Plans:['วิทยาศาสตร์–คณิตศาสตร์','คณิตศาสตร์–ภาษาอังกฤษ','ภาษาอังกฤษ–ภาษาจีน','ภาษาอังกฤษ–ภาษาญี่ปุ่น','ภาษา/มนุษยศาสตร์','ธุรกิจ/บริหาร','เทคโนโลยี/ดิจิทัล','ศิลปะ/ออกแบบ','กีฬา','อื่น ๆ'],
    vocational:['ช่างยนต์','ช่างไฟฟ้า','ช่างอิเล็กทรอนิกส์','ช่างก่อสร้าง','เทคนิคคอมพิวเตอร์','เทคโนโลยีสารสนเทศ','การบัญชี','การตลาด','ธุรกิจค้าปลีก','คอมพิวเตอร์ธุรกิจ','การท่องเที่ยว','การโรงแรม','อาหารและโภชนาการ','แฟชั่นและสิ่งทอ','ศิลปกรรม/ออกแบบ','เกษตรกรรม','อื่น ๆ'],
    factors:['ความชอบของตนเอง','ความถนัดของตนเอง','ผลการเรียน','อาชีพที่สนใจ','ผู้ปกครอง','ครู','เพื่อน','รุ่นพี่','ชื่อเสียงของสถานศึกษา','ค่าใช้จ่าย','ระยะทาง/การเดินทาง','ทุนการศึกษา','อื่น ๆ'],
    advisors:['พ่อ','แม่','ผู้ปกครอง','ครูประจำชั้น','ครูแนะแนว','ครูผู้สอน','พี่/ญาติ','เพื่อน','รุ่นพี่','ยังไม่ได้ปรึกษาใคร','อื่น ๆ'],
    info:['รายละเอียดแผนการเรียน','รายวิชาที่ต้องเรียน','สาขาสายอาชีพ','คุณสมบัติการสมัคร','วันรับสมัคร','ค่าใช้จ่าย','ทุนการศึกษา','สถานที่เรียน','การเดินทาง','หอพัก','แนวทางศึกษาต่อ','อาชีพในอนาคต','ต้องการพูดคุยกับครูแนะแนว','อื่น ๆ']
  };
  let student=null,step=0,teacherCode='',teacherRows=[],form=blank();
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const arr=v=>Array.isArray(v)?v:(v?[v]:[]);
  function blank(){return{likedSubjects:[],goodSubjects:[],interests:[],strengths:[],pathway:'',otherPath:'',plan1:'',plan2:'',plan3:'',institution1:'',institutionReason1:'',institution2:'',institution3:'',career1:'',career2:'',career3:'',careerReason1:'',factors:[],advisors:[],infoNeeded:[],confidence:0}}
  function view(id){['homeView','studentView','teacherView'].forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:'smooth'})}
  function msg(id,text='',ok=false){const e=$(id);if(!e)return;e.textContent=text;e.style.color=ok?'var(--good)':'var(--bad)'}
  function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
  function busy(el,on){if(el)el.classList.toggle('loading',on)}
  function apiReady(){if(!API_URL)throw new Error('ระบบยังไม่ได้เชื่อม Google Sheet กรุณาให้ผู้ดูแลตั้งค่า API_URL ในไฟล์ config.js')}
  function jsonp(params={},timeout=15000){apiReady();return new Promise((resolve,reject)=>{const cb='__msp_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),u=new URL(API_URL);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,typeof v==='object'?JSON.stringify(v):String(v??'')));u.searchParams.set('callback',cb);let timer;const clean=()=>{clearTimeout(timer);delete window[cb];s.remove()};window[cb]=d=>{clean();d&&d.ok===false?reject(new Error(d.message||'เกิดข้อผิดพลาด')):resolve(d)};s.onerror=()=>{clean();reject(new Error('ไม่สามารถเชื่อมต่อฐานข้อมูลได้'))};timer=setTimeout(()=>{clean();reject(new Error('การเชื่อมต่อใช้เวลานานเกินไป กรุณาลองใหม่'))},timeout);s.src=u.toString();document.head.appendChild(s)})}
  async function post(action,payload){apiReady();const body=new URLSearchParams();body.set('action',action);body.set('payload',JSON.stringify(payload||{}));await fetch(API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});return{ok:true}}
  async function loginStudent(){const id=$('studentId').value.trim();msg('loginMessage');if(!id)return msg('loginMessage','กรุณากรอกรหัสประจำตัวนักเรียน');const card=document.querySelector('.login-card');try{busy(card,true);const r=await jsonp({action:'student',studentId:id});student=r.student||r;form={...blank(),...(student.existing||{})};step=0;renderStudent();view('studentView')}catch(e){msg('loginMessage',e.message)}finally{busy(card,false)}}
  function renderStudent(){const initials=[student.firstName,student.lastName].filter(Boolean).map(x=>String(x).trim()[0]||'').join('').slice(0,2)||'ST';$('studentInitials').textContent=initials;$('studentName').textContent=student.fullName||[student.firstName,student.lastName].filter(Boolean).join(' ')||'นักเรียน';$('studentMeta').textContent=`${student.level||'ม.3'}/${student.room||'-'} · เลขที่ ${student.number||'-'}`;renderNav();renderStep()}
  function renderNav(){$('stepNav').innerHTML=STEPS.map((s,i)=>`<button type="button" data-step="${i}" class="${i===step?'active':''} ${i<step?'done':''}"><span class="step-dot">${i<step?'✓':i+1}</span><span>${esc(s[0])}</span></button>`).join('');$('stepNav').querySelectorAll('button').forEach(b=>b.onclick=()=>{const t=+b.dataset.step;collect();if(t<=step||t===step+1){step=t;renderNav();renderStep()}})}
  function renderStep(){const meta=STEPS[step];$('stepKicker').textContent=`ขั้นตอนที่ ${step+1} จาก ${STEPS.length}`;$('stepTitle').textContent=meta[0];$('stepDescription').textContent=meta[1];$('stepContent').innerHTML=stepHtml(step);$('prevBtn').style.visibility=step===0?'hidden':'visible';$('saveDraftBtn').classList.toggle('hidden',step===5);$('nextBtn').textContent=step===5?'ยืนยันข้อมูล':'ถัดไป';$('saveState').textContent=form.status==='ยืนยันแล้ว'?'เคยยืนยันข้อมูลแล้ว':(student.existing?'มีข้อมูลเดิม':'ยังไม่ได้บันทึก');const pct=Math.round(step/(STEPS.length-1)*100);$('progressText').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;msg('wizardMessage');bindStep()}
  function chips(name,options,selected,max){const set=new Set(arr(selected));return`<div class="chip-grid" data-max="${max||99}" data-group="${name}">${options.map((x,i)=>`<span class="choice-chip"><input type="checkbox" name="${name}" id="${name}_${i}" value="${esc(x)}" ${set.has(x)?'checked':''}><label for="${name}_${i}">${esc(x)}</label></span>`).join('')}</div>`}
  function stepHtml(s){
    if(s===0)return`<div class="question-block"><h3>วิชาที่ฉันชอบ</h3><p class="hint">เลือกได้ไม่เกิน 3 วิชา</p>${chips('likedSubjects',LISTS.subjects,form.likedSubjects,3)}</div><div class="question-block"><h3>วิชาที่ฉันคิดว่าตนเองทำได้ดี</h3><p class="hint">เลือกได้ไม่เกิน 3 วิชา</p>${chips('goodSubjects',LISTS.subjects,form.goodSubjects,3)}</div><div class="question-block"><h3>กิจกรรมหรือเรื่องที่ฉันสนใจ</h3><p class="hint">เลือกได้ไม่เกิน 5 ข้อ</p>${chips('interests',LISTS.interests,form.interests,5)}</div><div class="question-block"><h3>จุดเด่นของฉัน</h3><p class="hint">เลือกได้ไม่เกิน 3 ข้อ</p>${chips('strengths',LISTS.strengths,form.strengths,3)}</div>`;
    if(s===1)return`<div class="question-block"><h3>หลังจบชั้น ม.3 ฉันสนใจเรียนต่อแบบใด</h3><p class="hint">เลือกตัวเลือกที่ตรงกับความคิดของเราตอนนี้มากที่สุด</p><div class="radio-grid">${LISTS.pathways.map((p,i)=>`<span class="radio-card"><input type="radio" name="pathway" id="path_${i}" value="${esc(p[0])}" ${form.pathway===p[0]?'checked':''}><label for="path_${i}"><strong>${esc(p[0])}</strong><small>${esc(p[1])}</small></label></span>`).join('')}</div></div><div id="otherPathBox" class="field ${form.pathway==='อื่น ๆ'?'':'hidden'}"><label for="otherPath">ระบุเส้นทางอื่นที่สนใจ</label><input id="otherPath" class="input" value="${esc(form.otherPath)}" placeholder="เช่น เรียนหลักสูตร..." /></div>`;
    if(s===2){const list=form.pathway==='สายอาชีพ ปวช.'?LISTS.vocational:form.pathway==='ม.4 สายสามัญ'?LISTS.m4Plans:[];const label=form.pathway==='สายอาชีพ ปวช.'?'สาขาวิชาหรือกลุ่มอาชีพ':form.pathway==='ม.4 สายสามัญ'?'แผนการเรียน':'หลักสูตร/แนวทาง';if(form.pathway==='ยังไม่แน่ใจ')return`<div class="info-box"><strong>ยังไม่แน่ใจก็ได้</strong><br>สามารถข้ามส่วนนี้ แล้วระบุสถาบัน อาชีพ หรือข้อมูลที่ต้องการเพิ่มเติม เพื่อให้ครูช่วยแนะแนวต่อได้</div>`;return`<div class="question-block"><h3>${esc(label)}ที่ฉันสนใจ</h3><p class="hint">เรียงได้สูงสุด 3 อันดับ</p><div class="form-grid three">${[1,2,3].map(n=>`<div class="field"><label for="plan${n}">อันดับ ${n}</label><input id="plan${n}" class="input" list="planOptions" value="${esc(form['plan'+n])}" placeholder="พิมพ์หรือเลือกจากรายการ" /></div>`).join('')}</div><datalist id="planOptions">${list.map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist></div>`}
    if(s===3)return`<div class="question-block"><h3>สถานศึกษาที่ฉันสนใจ</h3><p class="hint">กรอกได้สูงสุด 3 แห่ง หากยังไม่มีสถาบันในใจ สามารถเว้นว่างได้</p><div class="form-grid three">${[1,2,3].map(n=>`<div class="field"><label for="institution${n}">อันดับ ${n}</label><input id="institution${n}" class="input" value="${esc(form['institution'+n])}" placeholder="ชื่อโรงเรียน/วิทยาลัย/สถานศึกษา" /></div>`).join('')}</div></div><div class="field"><label for="institutionReason1">เหตุผลที่สนใจสถาบันอันดับ 1</label><textarea id="institutionReason1" class="input textarea" placeholder="เช่น มีแผนการเรียนที่สนใจ ใกล้บ้าน ค่าใช้จ่ายเหมาะสม">${esc(form.institutionReason1)}</textarea></div>`;
    if(s===4)return`<div class="question-block"><h3>ในอนาคตฉันสนใจทำอาชีพอะไร</h3><p class="hint">หากยังไม่แน่ใจ สามารถเว้นว่างได้</p><div class="form-grid three">${[1,2,3].map(n=>`<div class="field"><label for="career${n}">อันดับ ${n}</label><input id="career${n}" class="input" value="${esc(form['career'+n])}" placeholder="ชื่ออาชีพ" /></div>`).join('')}</div></div><div class="field question-block"><label for="careerReason1">เพราะอะไรฉันจึงสนใจอาชีพอันดับ 1</label><textarea id="careerReason1" class="input textarea">${esc(form.careerReason1)}</textarea></div><div class="question-block"><h3>อะไรมีผลต่อการเลือกเส้นทางเรียนต่อของฉัน</h3>${chips('factors',LISTS.factors,form.factors,99)}</div><div class="question-block"><h3>ฉันปรึกษาใครเกี่ยวกับการเรียนต่อ</h3>${chips('advisors',LISTS.advisors,form.advisors,99)}</div><div class="question-block"><h3>ฉันยังต้องการข้อมูลเรื่องใดเพิ่มเติม</h3>${chips('infoNeeded',LISTS.info,form.infoNeeded,99)}</div><div class="question-block"><h3>ตอนนี้ฉันมั่นใจในเส้นทางที่เลือกมากน้อยเพียงใด</h3><div class="confidence-grid">${[1,2,3,4,5].map(n=>`<span><input type="radio" name="confidence" id="confidence_${n}" value="${n}" ${+form.confidence===n?'checked':''}><label for="confidence_${n}"><strong>${n}</strong><small>${['','ยังไม่มั่นใจ','เล็กน้อย','ปานกลาง','ค่อนข้างมั่นใจ','มั่นใจมาก'][n]}</small></label></span>`).join('')}</div></div>`;
    return summary();
  }
  function summary(){const path=form.pathway==='อื่น ๆ'?(form.otherPath||'อื่น ๆ'):(form.pathway||'-');const box=(l,v,f=false)=>`<div class="summary-box ${f?'full-span':''}"><div class="summary-label">${esc(l)}</div><div class="summary-value">${esc(v||'-')}</div></div>`;return`<div class="summary-grid">${box('นักเรียน',`${student.fullName||''} · ${student.level||'ม.3'}/${student.room||'-'}`,true)}${box('วิชาที่ชอบ',arr(form.likedSubjects).join(', '))}${box('วิชาที่ทำได้ดี',arr(form.goodSubjects).join(', '))}${box('สิ่งที่สนใจ',arr(form.interests).join(', '))}${box('จุดเด่น',arr(form.strengths).join(', '))}${box('เส้นทางหลัง ม.3',path)}${box('แผน/สาขาอันดับ 1',form.plan1||(form.pathway==='ยังไม่แน่ใจ'?'ยังไม่แน่ใจ':''))}${box('สถาบันที่อยู่ในใจ',form.institution1||'ยังไม่มีในใจ')}${box('อาชีพที่สนใจ',form.career1||'ยังไม่แน่ใจ')}${box('ระดับความมั่นใจ',`${+form.confidence||0} / 5`)}${box('ข้อมูลที่ต้องการเพิ่มเติม',arr(form.infoNeeded).join(', '),true)}</div><div class="info-box" style="margin-top:16px">ผลนี้ใช้เพื่อช่วยให้นักเรียนเห็นภาพของตนเองและใช้ประกอบการพูดคุยกับครู/ผู้ปกครอง ไม่ใช่การตัดสินว่านักเรียน “เหมาะ” หรือ “ไม่เหมาะ” กับเส้นทางใด</div>`}
  function bindStep(){document.querySelectorAll('[data-group]').forEach(g=>{const max=+g.dataset.max||99;g.querySelectorAll('input').forEach(i=>i.onchange=()=>{if(g.querySelectorAll('input:checked').length>max){i.checked=false;toast(`เลือกได้ไม่เกิน ${max} ข้อ`)}})});document.querySelectorAll('input[name="pathway"]').forEach(i=>i.onchange=()=>{form.pathway=i.value;const b=$('otherPathBox');if(b)b.classList.toggle('hidden',i.value!=='อื่น ๆ')})}
  const selected=name=>[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value);const val=id=>$(id)?$(id).value.trim():'';
  function collect(){if(step===0){form.likedSubjects=selected('likedSubjects');form.goodSubjects=selected('goodSubjects');form.interests=selected('interests');form.strengths=selected('strengths')}if(step===1){const p=document.querySelector('input[name="pathway"]:checked');form.pathway=p?p.value:form.pathway;form.otherPath=val('otherPath')}if(step===2){form.plan1=val('plan1');form.plan2=val('plan2');form.plan3=val('plan3')}if(step===3){form.institution1=val('institution1');form.institutionReason1=val('institutionReason1');form.institution2=val('institution2');form.institution3=val('institution3')}if(step===4){form.career1=val('career1');form.career2=val('career2');form.career3=val('career3');form.careerReason1=val('careerReason1');form.factors=selected('factors');form.advisors=selected('advisors');form.infoNeeded=selected('infoNeeded');const c=document.querySelector('input[name="confidence"]:checked');form.confidence=c?+c.value:form.confidence}}
  function validate(){if(step===1&&!form.pathway)return'กรุณาเลือกเส้นทางหลังจบ ม.3';if(step===4&&!+form.confidence)return'กรุณาเลือกระดับความมั่นใจ';return''}
  function next(){collect();const e=validate();if(e)return msg('wizardMessage',e);if(step<5){step++;renderNav();renderStep();window.scrollTo({top:0,behavior:'smooth'})}else confirm()}
  function prev(){collect();if(step>0){step--;renderNav();renderStep();window.scrollTo({top:0,behavior:'smooth'})}}
  async function saveDraft(){collect();try{busy(document.querySelector('.wizard-panel'),true);await post('saveSurvey',{...form,studentId:student.studentId,confirmed:false});$('saveState').textContent='บันทึกร่างแล้ว';toast('บันทึกร่างแล้ว')}catch(e){msg('wizardMessage',e.message)}finally{busy(document.querySelector('.wizard-panel'),false)}}
  async function confirm(){collect();try{busy(document.querySelector('.wizard-panel'),true);await post('saveSurvey',{...form,studentId:student.studentId,confirmed:true});$('stepContent').innerHTML=`<div style="text-align:center;padding:55px 16px"><div style="font-size:56px;color:var(--teal)">✓</div><h2 style="color:var(--navy);margin:8px 0">ยืนยันข้อมูลเรียบร้อยแล้ว</h2><p class="muted">ข้อมูลถูกส่งไปยังฐานข้อมูลเพื่อใช้ประกอบการแนะแนว</p><button id="finishBtn" class="btn btn-primary" type="button">กลับหน้าหลัก</button></div>`;$('prevBtn').classList.add('hidden');$('saveDraftBtn').classList.add('hidden');$('nextBtn').classList.add('hidden');$('progressText').textContent='100%';$('progressBar').style.width='100%';$('finishBtn').onclick=logoutStudent}catch(e){msg('wizardMessage',e.message)}finally{busy(document.querySelector('.wizard-panel'),false)}}
  function logoutStudent(){student=null;form=blank();step=0;$('studentId').value='';view('homeView')}
  async function loginTeacher(){const code=$('teacherCode').value.trim();msg('teacherLoginMessage');if(!code)return msg('teacherLoginMessage','กรุณากรอกรหัสครู');try{busy(document.querySelector('#teacherDialog .modal-card'),true);const r=await jsonp({action:'teacherLogin',code});if(!r.ok)throw new Error(r.message||'รหัสครูไม่ถูกต้อง');teacherCode=code;$('teacherDialog').close();await loadTeacher()}catch(e){msg('teacherLoginMessage',e.message)}finally{busy(document.querySelector('#teacherDialog .modal-card'),false)}}
  async function loadTeacher(){try{view('teacherView');const r=await jsonp({action:'dashboard',code:teacherCode});teacherRows=r.students||[];renderKpis(r.stats||{});renderTable()}catch(e){toast(e.message);logoutTeacher()}}
  function renderKpis(s){const data=[['นักเรียนทั้งหมด',s.totalStudents||0],['ตอบแล้ว',s.responded||0],['ยืนยันแล้ว',s.confirmed||0],['ควรแนะแนว',s.guidance||0],['สนใจ ม.4',s.m4||0],['สนใจ ปวช.',s.vocational||0],['ยังไม่แน่ใจ',s.unsure||0]];$('kpiGrid').innerHTML=data.map(([l,n])=>`<div class="kpi"><strong>${esc(n)}</strong><span>${esc(l)}</span></div>`).join('')}
  function badge(s){const c=s==='ควรแนะแนว'?'badge-bad':s==='ควรติดตาม'?'badge-warn':'badge-good';return`<span class="badge ${c}">${esc(s||'ปกติ')}</span>`}
  function renderTable(){const q=$('teacherSearch').value.trim().toLowerCase(),f=$('teacherFilter').value,rows=teacherRows.filter(r=>(!f||r.guidanceStatus===f)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)));$('teacherTableBody').innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong><br><span class="muted">${esc(r.studentId)}</span></td><td>${esc(r.room)}</td><td>${esc(r.pathway||'-')}</td><td>${esc(r.plan1||'-')}</td><td>${esc(r.institution1||'-')}</td><td>${esc(r.career1||'-')}</td><td>${esc(r.confidence||0)}/5</td><td>${badge(r.guidanceStatus)}</td><td><button class="mini-btn" data-note="${esc(r.studentId)}" type="button">บันทึกครู</button></td></tr>`).join(''):`<tr><td colspan="9" style="text-align:center;padding:30px;color:var(--muted)">ไม่พบข้อมูล</td></tr>`;$('teacherTableBody').querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>openNote(b.dataset.note))}
  function openNote(id){const r=teacherRows.find(x=>String(x.studentId)===String(id));$('noteStudentId').value=id;$('noteStudentName').textContent=r?r.name:id;$('noteText').value=r?.teacherNote||'';$('noteStatus').value=r?.counselorStatus||'ยังไม่ได้ให้คำปรึกษา';msg('noteMessage');$('noteDialog').showModal()}
  async function saveNote(){try{busy(document.querySelector('#noteDialog .modal-card'),true);await post('saveCounselorNote',{code:teacherCode,studentId:$('noteStudentId').value,note:$('noteText').value,status:$('noteStatus').value});$('noteDialog').close();toast('บันทึกความคิดเห็นครูแล้ว');setTimeout(loadTeacher,700)}catch(e){msg('noteMessage',e.message)}finally{busy(document.querySelector('#noteDialog .modal-card'),false)}}
  function logoutTeacher(){teacherCode='';teacherRows=[];$('teacherCode').value='';view('homeView')}
  $('studentLoginBtn').onclick=loginStudent;$('studentId').onkeydown=e=>{if(e.key==='Enter')loginStudent()};$('studentLogoutBtn').onclick=logoutStudent;$('prevBtn').onclick=prev;$('nextBtn').onclick=next;$('saveDraftBtn').onclick=saveDraft;$('teacherOpenBtn').onclick=()=>{msg('teacherLoginMessage');$('teacherDialog').showModal();setTimeout(()=>$('teacherCode').focus(),50)};$('teacherLoginBtn').onclick=loginTeacher;$('teacherCode').onkeydown=e=>{if(e.key==='Enter')loginTeacher()};$('teacherLogoutBtn').onclick=logoutTeacher;$('teacherSearch').oninput=renderTable;$('teacherFilter').onchange=renderTable;$('saveNoteBtn').onclick=saveNote;document.querySelectorAll('[data-home]').forEach(a=>a.onclick=e=>{e.preventDefault();view('homeView')});
})();
